### ISSUE TITLE
Contribution intentions for Kuska

### ISSUE THREAD

**Issue by mycognosist** [Kuska-ssb/kuska-ssb#13]
@adria0 

In the next 2-3 months we will be writing a high-level API on top of Kuska-ssb as part of PeachCloud development efforts. This work is taking place in the [golgi repo](https://git.coopcloud.tech/glyph/golgi) and will allow us to interact with the go-sbot. We hope to provide a convenient library for other Rust developers to build Scuttlebutt applications.

I will have some contributions for Kuska-ssb along the way, such as satisfying `clippy` and adding any low-level helper functions or types which might be missing.

What is your preferred way for me to work? Would you be happy for me to continue making PR's to this library for you to review? Or would you prefer me to fork the repo? I'm not sure what your availability is like at the moment so I'm trying to find the best solution for both of us :)

**Comment by adria0** [comment]
@mycognosist I'm really happy you contributing to the repo, so l'll allocate some of my time to review your PR's 👍 

let's me first fix the .github CI build

**Comment by mycognosist** [comment]
@adria0 

This is great news. Thank you!

**Comment by adria0** [comment]
Plz, close the issue if you think that is ready for it :)
