### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by mycognosist** [Kuska-ssb/kuska-ssb#23]
@adria0

Would you be willing to publish this as a crate?

I am ready to publish the [golgi](https://git.coopcloud.tech/golgi-ssb/golgi) crate but cannot do that because it currently depends on kuska as a git dependency.

**Comment by adria0** [comment]
@mycognosist, sure, why not.

What name do you prefer in the toml `authors`? https://github.com/Kuska-ssb/ssb/blob/master/Cargo.toml#L4

**Comment by mycognosist** [comment]
@adria0 

Great!

`Andrew Reid <glyph@mycelial.technology>`

**Comment by adria0** [comment]
@mycognosist done! https://crates.io/crates/kuska-ssb/

**Comment by mycognosist** [comment]
Amazing, thanks @adria0. I really appreciate how helpful and receptive you've been to my contributions. Thank you!
